
export const dataConsultas =[
    {
        id:1,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:2,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:3,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:4,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:5,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:6,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:7,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:8,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:9,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:10,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:1,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:2,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:3,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:4,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:5,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:6,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:7,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:8,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:9,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
    {
        id:10,
        motivo: 'xxxxxxxxxxxxxxxxxx',
        procedimiento: 'xxxxxxxxxxxxxxxxx',
        fecha : 'Junio 20 de 2022',
        precio: 1234567,
    },
]